# Generated by Django 3.1.5 on 2021-01-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito')], max_length=6)),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_posted', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
