# Generated by Django 3.1.5 on 2021-01-23 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=4)),
                ('account', models.CharField(max_length=11)),
                ('digit', models.CharField(max_length=1)),
                ('type_account', models.CharField(choices=[('CURRENT_ACCOUNT', 'Conta corrente'), ('SAVINGS_ACCOUNT', 'Conta poupança')], default='CURRENT_ACCOUNT', max_length=15)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bank_account.bank')),
            ],
        ),
    ]
